language: java

sudo: false
dist: trusty
jdk:
  - oraclejdk8

install:
  - mvn --version
  - java -version

script: mvn verify

after_success:
  - mvn clean cobertura:cobertura org.jwtk.coveralls:coveralls-maven-plugin:report
