name: Coveralls

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coveralls:
    if: github.repository_owner == 'hazendaz'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: maven
          distribution: temurin
          java-version: 21
      - name: Report Coverage to Coveralls for Pull Requests
        if: github.event_name == 'pull_request'
        run: ./mvnw test jacoco:report coveralls:report --batch-mode --no-transfer-progress --quiet --show-version -Dlicense.skip=true -DpullRequest=$PR_NUMBER -DrepoToken=$GITHUB_TOKEN -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Report Coverage to Coveralls for General Push
        if: github.event_name == 'push'
        run: |
          ./mvnw install --batch-mode --no-transfer-progress --quiet --show-version -Dlicense.skip=true |
          ./mvnw jacoco:report coveralls:report --batch-mode --no-transfer-progress -Dcoveralls.plugin=4.7.1-SNAPSHOT -DrepoToken=$GITHUB_TOKEN -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
